### ISSUE TITLE
Only 1st row of Buttons displayed

### ISSUE THREAD

**Issue by diesocke** [quaap/PhoneFoneFun#2]
Hi!

Using V1.2 in Galaxy S7 Edge with Android 7.0. App Displays only 1st row  (1, 2 and 3). How can I display the other button rows?

**Comment by quaap** [comment]
Strange.  I've tested mostly with 7.1 (what I have on my phone). I'll set up a 7.0 emulator later today and test it out.  Thanks for reporting!

**Comment by diesocke** [comment]
Don't know what is different, but now all  buttons are displayed.

**Comment by quaap** [comment]
Sorry, my family is in the middle of a complicated move and I've not had a chance to get back to you.  I couldn't reproduce this on the emulator, either.  If the problem re-occurs, or you get new information about why it might have happened, feel free to re-open this issue!  Thanks for reporting!
