### ISSUE TITLE
Set tts language

### ISSUE THREAD

**Issue by treakiandroid** [quaap/PhoneFoneFun#3]
Please tell the tts engine that it should speak english. Not just use system language. I hadd0 to switch my systemlanguage to english for  the app to work correctly

**Comment by treakiandroid** [comment]
Thanks

**Comment by quaap** [comment]
Ah, I can see how that might fail!  Thanks!

**Comment by treakiandroid** [comment]
Thanks now it works, if you would send me a list of the spoken text i can translate it to german it you want (I'm native speaker)
